{{ if .Values.openunison.naas.groups.internal.enabled }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-{{ .Release.Name }}-cluster-administrators{{ .Values.openunison.naas.groups.internal.suffix }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
subjects:
- kind: Group
  name: k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.internal.suffix }}
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: openunison-{{ .Values.openunison.orchestra_release_name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}