{{ if .Values.cicd_proxy.network.network_policies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cicd-proxy
    app.kubernetes.io/instance: cicd-proxy-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: cicd-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{ end }}