network:
  openunison_host: "k8sou.apps.domain.int"
  dashboard_host: "k8sdb.apps.domain.int"
  api_server_host: "k8sapi.apps.domain.int"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-installer-master.tremolo.lan:6443
  createIngressCertificate: true
  ingress_type: nginx
  ingress_annotations: {}
  

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.io/tremolosecurity/openunison-k8s:latest"
amq_image: "docker.io/tremolosecurity/activemq-docker:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: true
myvd_configmap: myvd

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  enabled: true
certs:
  use_k8s_cm: false

trusted_certs: []


#active_directory:
#  base: cn=users,dc=ent2k12,dc=domain,dc=com
#  host: "192.168.2.75"
#  port: "636"
#  bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
#  con_type: ldaps
#  srv_dns: "false"

database:
  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://dbs.tremolo.lan:3308/unison
  user: root
  validation: SELECT 1

smtp:
  host: smtp.gmail.com
  port: 587
  user: donotreply@domain.com
  from: donotreply@domain.com
  tls: true

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true
  ca_secret_name: ou-tls-certificate

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels: []
  monitoring:
    enabled: true
    labels: []
  apiserver:
    enabled: true
    labels: []
  namespace_label: kubernetes.io/metadata.name
      

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []
  pullSecret: ""
  liveness_probe:
  - /usr/local/openunison/bin/check_alive.sh
  - "https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration"
  - "issuer"
  - "https://127.0.0.1:8443/check_alive"
  - "alive"
  readiness_probe:
  - /usr/local/openunison/bin/check_alive.sh
  - "https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration"
  - "issuer"
  - "https://127.0.0.1:8443/check_alive"
  - "alive"

operator:
  image: docker.io/tremolosecurity/openunison-kubernetes-operator:latest
  resources:
    requests:
      memory: 200Mi
      cpu: 0.3
    limits:
      memory: 200Mi
      cpu: 1.0

openunison:
  imagePullPolicy: Always
  replicas: 1
  non_secret_data: {}
  secrets: []
  env: {}
  portal_release_name: openunison
  authentication:
    refresh_token:
      grace_period_millis: 0
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  enable_activemq: true
  az_groups: []
  precheck:
    image: docker.io/tremolosecurity/python3
  use_standard_jit_workflow: true
  management_proxy:
    enabled: false
  naas:
    forms:
      new_namespace:
        use_default: true
    workflows:
      new_namespace:
        use_default: true
    groups:
      internal:
        enabled: true
        suffix: "-internal"
      external:
        suffix: "-external"
        enabled: false
        admin_group: "CN=openunison-admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
        cluster_admin_group: "CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
    reasons: []

crd:
  deploy: true
  betas: false