{{ if eq .Values.cicd-proxy.network.ingress_type "simple" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    {{ range $key,$value := .Values.cicd-proxy.network.ingress_annotations }}
    {{ $key }}: {{ quote $value }}
    {{ end }}
  name: cicdproxy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: cicdproxy-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-simple
    app.kubernetes.io/part-of: openunison
spec:
  rules:
  
  - host: {{ .Values.cicd-proxy.network.api_server_host }}
    http:
      paths:
      - backend:
          service:
            name: kube-oidc-proxy-{{ .Release.Name }}
            port:
              number: 443
        path: "/"
        pathType: Prefix
  
  tls:
  - hosts:
    - {{ .Values.cicd-proxy.network.api_server_host }}
    secretName: cicd-proxy-tls-certificate
{{ end }}