{{ if eq .Values.cicd_proxy.network.ingress_type "istio" }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cicd-proxy-api-gateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cicd-proxy
    app.kubernetes.io/instance: cicd-proxy-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: cicd-proxy
spec:
  selector:
    {{ range $key,$value := .Values.cicd_proxy.network.istio.selectors }}
        {{ $key }}: {{ quote $value }}
    {{ end }}
  servers:
  - hosts:
    - {{ .Values.cicd_proxy.network.api_server_host }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - {{ .Values.cicd_proxy.network.api_server_host }}
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cicd-proxy-api-{{ .Release.Name }}-jetstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cicd-proxy
    app.kubernetes.io/instance: cicd-proxy-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: cicd-proxy
spec:
  gateways:
  - cicd-proxy-api-gateway-{{ .Release.Name }}
  hosts:
  - {{ .Values.cicd_proxy.network.api_server_host }}
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ .Values.cicd_proxy.network.api_server_host }}
    route:
    - destination:
        host: kube-oidc-proxy-{{ .Release.Name }}
        port:
          number: 443
{{ end }}