{{ if eq .Values.cicd_proxy.network.ingress_type "traefik" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .Values.cicd_proxy.network.traefik.entrypoints.tls }}"
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{ range $key,$value := .Values.cicd_proxy.network.ingress_annotations }}
    {{ $key }}: {{ quote $value }}
    {{ end }}
  name: cicd-proxy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cicd-proxy
    app.kubernetes.io/instance: cicd-proxy-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-traefik
    app.kubernetes.io/part-of: cicd-proxy
spec:
  rules:
  - host: {{ .Values.cicd_proxy.network.api_server_host }}
    http:
      paths:
      - backend:
          service:
            name: kube-oidc-proxy-{{ .Release.Name }}
            port:
              number: 443
        path: "/"
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.cicd_proxy.network.api_server_host }}
    secretName: cicd-proxy-tls-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-{{ .Release.Name }}-redirect-to-https
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.cicd_proxy.network.traefik.entrypoints.plaintext }}
  routes:
    - match: HostRegexp(`{{ .Values.cicd_proxy.network.api_server_host }}`)
      kind: Rule 
      services:
        - name: cicd-proxy-{{ .Release.Name }}
          port: 80
      middlewares:
        - name: redirect-https
          namespace: {{ .Release.Namespace }}
{{ end }}