{{ if .Values.cicd_proxy.explicit_certificate_trust }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oidc-ca
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.cicd_proxy.oidc.ca }}
{{ end }}
