# If set to true the CRDs will be deployed.  Otherwise the CRs are ignored.
crd:
  deploy: true
  betas: false
  webhooks: true

services:
  node_selectors: []
  pullSecret: ""

operator:
  image: docker.io/tremolosecurity/openunison-kubernetes-operator:latest
  resources:
    requests:
      memory: 200Mi
      cpu: 0.3
    limits:
      memory: 200Mi
      cpu: 1.0


  