---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonator-{{ .Release.Namespace }}-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: cicd-proxy
    app.kubernetes.io/instance: cicd-proxy-{{ .Release.Name }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cicd-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "20"
rules:
{{ if and .Values.cicd_proxy.impersonation .Values.cicd_proxy.impersonation.users }}
- apiGroups:
  - ""
  resources:
  - users
  verbs:
  - impersonate
  
  resourceNames:
  {{ range .Values.cicd_proxy.impersonation.users }}
  - "{{ . }}"
  {{ end }}
  {{ end }}
- apiGroups:
  - ""
  resources:
  - groups
  verbs:
  - impersonate
  resourceNames:
  - "system:authenticated"
  {{ if and .Values.cicd_proxy.impersonation .Values.cicd_proxy.impersonation.groups }}
  {{ range .Values.cicd_proxy.impersonation.groups }}
  - "{{ . }}"
  {{ end }}
  {{ end }}
{{ if and .Values.cicd_proxy.impersonation .Values.cicd_proxy.impersonation.serviceaccounts }}
{{ range .Values.cicd_proxy.impersonation.serviceaccounts }}
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
  namespace: .namespace
  resourceNames:
  - .name
  {{ end }}
{{ end }}
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "userextras/scopes"
  - "userextras/remote-client-ip"
  - "tokenreviews"
  # to support end user impersonation
  - "userextras/originaluser.jetstack.io-user"
  - "userextras/originaluser.jetstack.io-groups"
  - "userextras/originaluser.jetstack.io-extra"
  verbs:
  - "create"
  - "impersonate"
- apiGroups: 
  - "authorization.k8s.io"
  resources:
  - "subjectaccessreviews"
  verbs:
  - "create"
