{{ if .Values.openunison.naas.groups.external.enabled }}
---
apiVersion: openunison.tremolo.io/v1
kind: GroupMetaData
metadata:
  name: administrators
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-groupmetadata
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  groupName: administrators{{ .Values.openunison.naas.groups.external.suffix }}
  externalName: {{ .Values.openunison.naas.groups.external.adminGroup }}
---
apiVersion: openunison.tremolo.io/v1
kind: GroupMetaData
metadata:
  name: operations
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-groupmetadata
    app.kubernetes.io/part-of: openunison
spec:
  groupName: operations{{ .Values.openunison.naas.groups.external.suffix }}
  externalName: {{ .Values.openunison.naas.groups.external.operationsGroup }}
---
apiVersion: openunison.tremolo.io/v1
kind: GroupMetaData
metadata:
  name: k8s-cluster-k8s-administrators
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-groupmetadata
    app.kubernetes.io/part-of: openunison
spec:
  groupName: k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.external.suffix }}
  externalName: {{ .Values.openunison.naas.groups.external.clusterAdminGroup }}
{{ end }}