{{ if .Values.openunison.naas.groups.internal.enabled }}
---
kind: MessageListener
apiVersion: openunison.tremolo.io/v1
metadata:
  name: {{ .Values.openunison.naas.jobs.rebase.queuename }}
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.provisioning.listeners.UpdateApprovalAZListener
  params: []
{{ end }}
